---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: default
  playbook: playbook.yml

platforms:
  - name: ubuntu-15.04
    driver_config:
      image: ubuntu:15.04

busser:
  ruby_bindir: /usr/bin

suites:
  - name: default

